### ISSUE TITLE
Walk In Hypothesis 

### ISSUE THREAD

**Issue by MaikRe** [HULKs/hulk#1016]
Due to the rule changes our walk in hypothesis from the new penalty rules our robots expect to walk into the field from 20cm outside, even during normal testing. We should consider if we want this to be on the line rather than outside of it when we manually bring the robot into playing via the chest button.

**Comment by schmidma** [comment]
Vote to keep it simple and thus only a single walk-in... Then nobody has to think which state is leading to what position. And additionally, the look-around is going to be tuned for that outside the side lines

**Comment by MaikRe** [comment]
Only comment was to keep it as it is which I can support.
