### ISSUE TITLE
Pepsi upload, poweroff, etc. subcommands fail after flashing 5.6.0 image

### ISSUE THREAD

**Issue by julianschuler** [HULKs/hulk#102]
After flashing the `5.6.0` image, pepsi subcommands such as upload, reboot and poweroff fail with error messages similar to the following:

```
Failed to power off system via logind: Interactive authentication required.
```

This seems to be an error of insufficent permissions for the systemd commands (`systemctl`, `poweroff`, `reboot`), a simple workaround may be to add `sudo` before each of them whithin pepsi.

**Comment by schmidma** [comment]
Closed with https://github.com/HULKs/meta-nao/commit/16938fba1f74b12c0e509ef19c253b087ee98bf4
