### ISSUE TITLE
No kick targets when obstacle is near goal

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#1050]
In this scenario there are no kick targets even though there is plenty of space to kick into the goal.
@schmidma suggested this may be because one of the kick targets is blocked and the other one is split into two because of obstacle intersections.
But the positions the ball would end up at with the split kick targets aren't inside the field anymore, leading to them being dropped too.
We should always have at least one kick target if there is a ball.
The dribble action executes `Stand` here.

Tthis may be related to #1012, @Vivituhh

![image](https://github.com/HULKs/hulk/assets/33729490/b6f8cd8f-38aa-4046-b41d-c4c2ab111eb1)

**Comment by MaikRe** [comment]
Suggestion:
what if this is a  loop for some n-parameter times that as long as it is empty repeats
```rust
let kick_targets = collect_kick_targets(
            *context.ground_to_field,
            context.field_dimensions,
            &obstacle_circles,
            ball_position,
            *context.max_kick_around_obstacle_angle,
            context.find_kick_targets,
            *context.corner_kick_strength,
        );
```
And instead of statically defined kick targets for the left and right goal
```rust
fn generate_goal_line_kick_targets(
    field_dimensions: &FieldDimensions,
    field_to_ground: Isometry2<Field, Ground>,
) -> Vec<KickTarget> {
    let left_goal_half = field_to_ground
        * point![
            field_dimensions.length / 2.0,
            field_dimensions.goal_inner_width / 4.0
        ];
    let right_goal_half = field_to_ground
        * point![
            field_dimensions.length / 2.0,
            -field_dimensions.goal_inner_width / 4.0
        ];
    vec![
        KickTarget::new(left_goal_half),
        KickTarget::new(right_goal_half),
    ]
}
```
we have new values instead of the ```4.0``` each time we call it to iterate through a few possible kick target locations in the goal, i.e. if there are none available in the left or right half of goal try the left or right quarter of the goal or left and right eight of the goal?
Thoughts?

**Comment by knoellle** [comment]
AFAIK the problem is not a lack of positions that we want to kick the ball to but rather some logic error in the kick target generation.

**Comment by MaikRe** [comment]
```rust
match closest_intersecting_obstacle {
                Some(circle) => {
                    let TwoLineSegments(left_tangent, right_tangent) =
                        circle.tangents_with_point(ball_position).unwrap();
                    [left_tangent, right_tangent]
                        .into_iter()
                        .map(|tangent| {
                            let kick_direction = (tangent.0 - ball_position).normalize();
                            // TODO: drop this constant?
                            ball_position + kick_direction * 2.0
                        })
                        .filter(|&position| {
                            field_dimensions.is_inside_field(ground_to_field * position)
                        })
                        .map(KickTarget::new)
                        .collect()
                }
                None => vec![target],
            }
```
I see what you mean now, it is probably this combination of mapping the tangent to some new position and filtering that position if it is outside of the field?
