### ISSUE TITLE
Buffered watch panics on sole writer

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#1127]
Notifying readers when dropping a sender guard panics if there are no more readers.

Failing testcase:
```rs
#[test]
fn sender_guard_dropped_without_receivers() {
    let (mut writer, reader) = channel(0);
    drop(reader);
    writer.borrow_mut();
}
```

**Comment by schmidma** [comment]
This is fixed in #990 (https://github.com/HULKs/hulk/pull/990/files#diff-2f816d03b6d5d20e2c876e634944f306fd579ed65b5eecac635f3728446f1994R112) but I can extract that from this PR and make a separate one as this is not directly related to #990
