### ISSUE TITLE
New Orientation is too correct

### ISSUE THREAD

**Issue by schluis** [HULKs/hulk#1149]
The new orientation Filter is too correct which might break things.
The center of mass / zero moment point is zero, if it is exactly at zero in robot coordinates. I.e. it is never desirable to get these to zero, because this is too far back, since the middle of the foot is more around `0.03`.

Task: Check all uses of center of mass / zero moment point and add a tunable offset if applicable

**Comment by MaikRe** [comment]
`default.json`
```json
477       "torso_tilt": 0.05,
```
It may be enough to adjust this to help with the torso tilt.
A known effect of the correct imu is a more correct center of mass, which then is also applied to the zero moment point.
The zero moment point determines where catching steps are placed, while the new imu determines necessary foot leveling.
It needs to be considered whether is is satisfactory to adjust existing catching step parameters
```json
    "catching_steps": {
      "catching_step_zero_moment_point_frame_count_threshold": 5,
      "use_catching_steps": true,
      "max_adjustment": 0.07,
      "midpoint": 0.3,
      "target_overestimation_factor": 1.05,
      "additional_foot_lift": 0.02
    },
```
Or possibly entirely new method of catching steps may be needed.
