### ISSUE TITLE
Head Movement -> Bring back the LookAt facilities for Twix worked on by Schmiddy

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#115]
There is a calibration branch that adds some GUI things to Twix for faster calibration. This needs to be looked at to decide what can be migrated and used.

Time Estimation: 1 day

**Comment by h3ndrk** [comment]
Schmiddy did: https://github.com/schmidma/nao/tree/calibration-mode

**Comment by tuxbotix** [comment]
Rough sketch of one idea:

The shortcuts make it easy to use the facility while the manual mode is for fine tuning work.
I recall from last year that the implementation by Maxi needed some precautions before using like the robot is safe, etc. We still need some way to know this or warn the users in the UI.

![image](https://user-images.githubusercontent.com/6742239/234351320-ca2106f3-259c-428f-9651-b8d46ce4f82f.png)

**Comment by tuxbotix** [comment]
I have an initial version of this. Ended up developing a bit different UI than the above idea;
It is quite minimal indeed but the radio buttons made the layout a bit simpler.

![Image](https://github.com/HULKs/hulk/assets/6742239/99eedc00-1e3e-45ef-ad2d-3ce2941e05b2)
