### ISSUE TITLE
Improve type `TwoLineSegments`

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#147]
This tuple type requires a manual `SerializeHierarchy` implementation. Maybe convert to a struct type and derive it simply?

**Comment by tuxbotix** [comment]
@h3ndrk This might sound like a stupid question, but is there a reason/ limitation that prevents us from extending `SerializedHierarchy` to support tuple structs or is there a technical reason not to? While I was doing #793 , I felt that tuple struct would still be cool to have.

I was wondering if field names can be made up with `0`, `1`, etc for serialization purposes or mark these cases as tuples, or use `(a, b, c)` syntax?

**Comment by h3ndrk** [comment]
I don't know of any technical limitation. The derive macro should™️ be implementable with `.0` etc. For deciding whether it is worth, have a look how often we would derive it for tuple structs and weigh it against the macro implementation effort.

**Comment by tuxbotix** [comment]
Thanks for the explanation. I think such a derive might ease the pains of refactoring a large amount of code (see #793).
You also have a good point on "how often", I'll give it a try to see how much pain can one get into :bomb:
