### ISSUE TITLE
Post Open Source Release TODOs

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#15]
- [x] SSH key removal
- [x] SSH key automatic login @schmidma
- [x] Make meta-hulks public (and the Rattenschwanz that is pulled by that)
- [x] All links to the old `HULKsCodeRelease` repo need to be updated to point to `hulk`
  - [x] Internal pages, Readmes
  - [x] hulks.de
  - [x] External RoboCup, pages etc.
- [x] Merge queue cannot be activated because `hulk` is not part of the closed beta. It will be generally available in Q4 2022, see https://github.com/github/roadmap/issues/370 **Edit: It is now available again for this repository and has been activated.**
- [x] CI Checks need to be added to branch protection rule once the first check had run
- [x] Migrate issues: **We are moving issues over if we see fit.**
- [x] Migrate PRs: **We are moving and rebasing PRs over if we see fit.**
- [x] Migrate labels
- [x] Work out a policy/workflow how to resubmit PRs to the new repository
  - Add `hulk` remote in your repository
  - Fetch it
  - Checkout the `main` branch of the `hulk` remote
  - Create the new branch that will contain the "rebased" changes
  - Then cherry-pick the individual commits e.g. `git cherry-pick beginning_hash..ending_hash` where `beginning_hash` and `ending_hash` are commit IDs. Careful, the `beginning_hash` has to be the base of your branch, not the first commit on top of that.
  - Push your new branch
  - Open a PR
  - Profit
- [x] readme title #331
- [x] Kanban board https://github.com/orgs/HULKs/projects/2
- [x] Was ist das? https://github.com/HULKs/hulk/blob/3e6e14baf99bf9b4f806a8787c117e7a8041513b/.github/workflows/documentation.yml#L22
  - is automatically filled by GitHub Actions with a token that has write access
- [x] Update Documentation hulks.de/hulk
- [x] Decide what to do with the wiki: The important stuff has been migrated
- [x] archive hulks/nao
- [ ] CI security considerations
  - Are there any keys/secrets accessible from inside the docker containers?
  - Do the containers have access to any system resources that could be a problem?

**Comment by Bendodroid** [comment]
Labels have been migrated.

**Comment by knoellle** [comment]
The only remaining point on this list are the security considerations.
I don't think our CI runners contain any secrets worth stealing and since I doubt anyone is going to slap a stamp of "yes, this is secure" on it, I suggest closing this issue.

**Comment by h3ndrk** [comment]
I agree, the runner currently only has access to the inside of the Docker containers which is a generic Linux filesystem without any secrets apart from the runner tokens (but these are there on every runner). Closing.
