### ISSUE TITLE
Keeper/Replacementkeeper Behavior improvements

### ISSUE THREAD

**Issue by PasGl** [HULKs/hulk#193]
During testing we saw a few minor issues with Keeper/Replacementkeeper Behavior:

 - When the keeper is the only player on the field, he wont become striker
 - When the ball vanishes the keeper does not reset his position to cover the center of the goal
 
We should create Behavior Simulator scenarios that reproduce these situations and fix the Behavior.

**Comment by MaikRe** [comment]
A quick behavior simulation confirms both of these facts, both that the keeper does not become striker and the keeper does not move back to cover the center of the goal and only moves back once a ball exists again.

**Comment by MaikRe** [comment]
Keeper seems to retain ball position from before ball dissapeared.

![Image](https://user-images.githubusercontent.com/87246463/233215118-36272bb0-3f7e-4c23-ac5d-653f2fb9b5b0.png)

**Comment by MaikRe** [comment]
>     * When the keeper is the only player on the field, he wont become striker

Seems to be intentional as seen in role_assignment line 493, Keeper and ReplacementKeeper wont become Searcher and therefore as far as I understand also not striker. This makes it a tactical decision of whether or not to keep the behavior as such.
One suggestion by @knoellle, adapt keeper behavior such that he walks closer to the ball and kicks it if only player, but does not run across the field with it, essentially a larger defense area.

**Comment by PasGl** [comment]
> > ```
> > * When the keeper is the only player on the field, he wont become striker
> > ```
> 
> Seems to be intentional as seen in role_assignment line 493, Keeper and ReplacementKeeper wont become Searcher and therefore as far as I understand also not striker. This makes it a tactical decision of whether or not to keep the behavior as such. One suggestion by @knoellle, adapt keeper behavior such that he walks closer to the ball and kicks it if only player, but does not run across the field with it, essentially a larger defense area.

I think what is happening here is in line 517.
No message has arrived, We see a ball, and (this is the problem) we still have a teamball ... The next question will be why the keeper still has a teamball in this situation.
