### ISSUE TITLE
Investigate robots not respecting ball is free

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#244]
In the game against Bembelbots today, we have multiple robots enter the center circle before the ball was free during an opponent kick off.

**Comment by schmidma** [comment]
@MaikRe checked, everything should be fine, the referee has some delay ;)

**Comment by Narcha** [comment]
This occurred again on multiple occasions today and yesterday.

**Comment by okiwi6** [comment]
Duplicate of #593
