### ISSUE TITLE
Essen fassen

### ISSUE THREAD

**Issue by jonathan-hellwig** [HULKs/hulk#256]
Bitte wählt ein Gericht von der Karte aus und kommentiert eure Wahl in diesem Issue.
Speisekarte: https://www.lieferando.de/speisekarte/asia-quick-suelldorfer-landstrasse

**Comment by PasGl** [comment]
Lamm Chili Basilikum (scharf)

**Comment by knoellle** [comment]
Rindfleisch (scharf)

**Comment by Narcha** [comment]
für Maik: Gebratene Nudeln mit gebackenem huhn
für mich: Gebratene Nudeln mit Sojasprossen

**Comment by h3ndrk** [comment]
Gebratene Nudeln mit gebackenem Hühnerfleisch

**Comment by tuxbotix** [comment]
Gebratener Reis mit gebackenem Hühnerfleisch (Sharf)

**Comment by MeiiMoon** [comment]
Gai Phad Gra Prau

**Comment by jonathan-hellwig** [comment]
Gebackene Ente (scharf)

**Comment by schmidma** [comment]
Poke Bowl Tofu

**Comment by pakonro** [comment]
Paul: Gebackene Ente in Kokosmilch 
Basma: Gebackenes Hühnerfleisch in Kokosmilch

**Comment by schluis** [comment]
Poke Bowl Ente

**Comment by julianschuler** [comment]
Gebratene Nudeln mit Sojasprossen

**Comment by Vivituhh** [comment]
Gebratene Nudeln mit gebackenem Hühnerfleisch

**Comment by okiwi6** [comment]
Nudeln mit Sojasprossen

**Comment by PatrickGoettsch** [comment]
Gebraten Nudeln mit Hühnerfleisch

**Comment by jonathan-hellwig** [comment]
Airbus: 
Tom Kha Gung (scharf)
Rindfleisch mit Soi-Sam

**Comment by thijmennijdam** [comment]
(DNT) Gebratene Nudeln mit Hühnerfleisch

**Comment by oxkitsune** [comment]
(DNT) Panäng Gai :netherlands:

**Comment by jonathan-hellwig** [comment]
Jonas: Gebratenes Hühnerfleisch in Kokosmilch (mittelscharf)

**Comment by Fyor** [comment]
(DNT) Gebratene Nudeln mit gebackenem Hühnerfleisch

**Comment by juellsprott** [comment]
(DNT) Shrimps (pikant, scharf)

**Comment by YukumoHunter** [comment]
(DNT) Gäng Khow Wan Nua (scharf) 🦀

**Comment by oskarbosgraaf** [comment]
(DNT) Gebratene Reis mit Rindfleisch

**Comment by Rickvanderveen** [comment]
(DNT) Gebratene Nudeln mit gebackenem Hühnerfleisch

**Comment by thijmennijdam** [comment]
thats all :)
