### ISSUE TITLE
Unreliable whistle detection

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#271]
Whistle detection is unreliable at the moment. During the game against B-Human, we had numerous missed whistles, and a few false positives as well.

Idea: make whistle sensitivity dynamic
- More sensitive in "Set"
- More sensitive for certain roles, e.g. the kickoff striker
- Ignore certain events, like during kickoff if the kickoff striker does not have a ball model

**Comment by h3ndrk** [comment]
FYI, in the last games, the parameters were not adapted. Since we seem to miss some samples, we might have missed the whistle very often. As a hotfix, the parameters for the number of recorded samples and the number of accepted samples with the threshold need to be doubled.
