### ISSUE TITLE
Pizza Bestellung

### ISSUE THREAD

**Issue by Vivituhh** [HULKs/hulk#305]
Pizza for tonight, write here what you want ASAP!! Until 20:10 !!!

https://www.liberta-pizza-fabrik.de/

**Comment by schmidma** [comment]
Maxi:
2x Pizza Brötchen mit Gouda, Hartkäse, Spinat und Knoblauch
Kobi-Dip

**Comment by okiwi6** [comment]
Ole:
2x Pizza Brötchen mit Gouda, Hartkäse, Spinat und Knoblauch

**Comment by julianschuler** [comment]
Rasmus und Julian: Pizza Monza (40cm)

**Comment by Vivituhh** [comment]
Pizza Holland (28cm)

**Comment by pakonro** [comment]
Basma: Pizza Monopoli
Paul: Pizza Curry Chicken

**Comment by OpenLarry** [comment]
Aaron (Nao Devils) 1x Gefüllte Pizzabrötchen mit Gouda, Hartkäse, Spinat und Knoblauch

**Comment by h3ndrk** [comment]
Pizza Western (40cm)

Mit Jonathan :heart:

**Comment by AliciaGa** [comment]
Alex NaoDevils: 1x Pizza Hawaii 33cm
Lisa NaoDevils: 1x Pizza Vegetaria 28cm

**Comment by Mahdokht1998** [comment]
Mahdokht: Pizzabrötchen mit Gouda und Thunfisch :)

**Comment by arnemoos** [comment]
1 x Pizza Palermo 28cm

**Comment by arnemoos** [comment]
Leon Nao Devils - Pizza Vegetaria

**Comment by jonathan-hellwig** [comment]
> Mahdokht: Pizzabrötchen mit Gouda und Thunfisch :)

Auch Nao Devils?

**Comment by arnemoos** [comment]
Mrunal Nao Devils - Gefüllte Pizzabrötchen mit Gouda, Hartkäse, Spinat und Knoblauch, 8 Stück

**Comment by knoellle** [comment]
Pizza Orient 33cm

**Comment by h3ndrk** [comment]
War lecker
