### ISSUE TITLE
Sit down motion stabilization

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#327]
The sit down motion should make sure the torso and head are in a stable position before exiting to unstiff.
Currently we have multiple robots that slowly tip over either to the front or back after finishing the sit down motion.

While this could be achieved by manually fiddling around with parameters for each robot, I think a better solution would involve checking the accelerometer to make sure the robot is actually upright and if not adjust the hip angles until it is.

**Comment by schluis** [comment]
Have a look at `stand_up_front.json` and do something similar using e.g. `exit_conditions`

**Comment by okiwi6** [comment]
Fixed in #329
