### ISSUE TITLE
Behavior Simulator Rewrite

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#36]
Build a new behavior simulator. The previous version broke with the recent framework changes.

# Basic idea:

Testing behavior is cumbersome.
Webots is very slow and and only simulates one robot.
Real robots are cumbersome to handle, especially when testing alone and/or with more than 1-2 robots.
A dedicated behavior simulator should solve this problem, allowing us to test behavior decisions and communication between robots in an easily repeatable manner.
For a given scenario file with a list of external events, the behavior simulator should output a state dump for every cycle.

# Interfacing with nodes:

Motion should be faked, i.e. when behavior request walking forward, the simulator simply advances the robots position.
Vision data such as ball position and self-location can be taken directly from the simulated environment, optionally with some (ideally deterministic) noise applied.
Communication between robots can also be done either directly or with simulated delay/jitter, packet loss, etc.

# Scenarios

The behavior simulator should be able to load files with scenarios and simulate the whole scenario as fast as possible.
For every simulation step, a dump of the whole control database for every cycle with all `AdditionalOutput`s enabled should be saved.
These "frames" can then be inspected retroactively with `twix` for example, jumping back and forth in the timeline without having to simulate anything.

Scenarios could also contain conditions that have to be fulfilled at certain points in time for automatic behavior testing.
These conditions could include:
- Goal scored after at most X time steps
- At most N robots within certain region (for testing kick-off/kick-in/illegal defender rules)
- ...

## Events

Any external factors that influence the game should be simulatable.

- Game controller messages
  - Goal scored
  - Robot (un-)penalized
  - ...
- Physical events
  - Ball teleports
  - Ball gains momentum (kicked by fake opponent)
  - Robot falls
- Miscellaneous
  - Whistle blown

# Previous version

The old behavior simulator is a rust program which can be found at `src/behavior_simulator`.
It would output a json file that would then be compiled into a react application at `tools/sprite`.
This architecture of having two separate programs is simple, but that doesn't mean the new version has to follow the same.
The viewer could be integrated directly into `twix` for example, or perhaps both simulation and timeline control could be done by a standalone application that allows editing the scenario, recalculating the frames after a changed event on the fly. Feel free to experiment.

# Some miscellaneous things to consider:

- should support up to 7 players (per side)
- Opponents. Either seperately simulated hulks or statically defined in scenario.
- Penalties
- Simulate fallen states/standup time
- (In-walk-)kicks

**Comment by h3ndrk** [comment]
Regarding tooling architecture, I think we need:

- Behavior simulator: Executes a subset of framework nodes, runs them in a simulation, records the time-series data to disk
- Data (Re)player/Seeker: Allows to play the recorded data (forward, backward, different playback speeds, jumping to timepoints, ...), uses the new communication server to make the data available to e.g. Twix

With this architecture, Twix does not need updates regarding the protocol. Only new panels etc. may need to be implemented.

**Comment by knoellle** [comment]
Updated main post with more information

**Comment by h3ndrk** [comment]
I would like to emphasize that we should aim for good interface separation because this allows to swap out parts of the architecture. In particular, it is probably not a good idea to implement parsing files directly in Twix. This makes Twix the only monolith that we could use to debug. The whole intention of the new communication server was to separate concerns better and make a behavior server implementation as easy as possible.
