### ISSUE TITLE
7v7 Games

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#37]
To prepare for the 7v7 games we will be facing in the upcoming RoboCup, we need to make some improvements as adding two additional robots per team on the rather small field will lead to chaos otherwise.

- Players enum
- Init positions
- Ready positions
- New Roles

(old ... partially obsolete)
- The main thing will be to implement new kick decisions to pass the ball to other players to avoid having to walk long distances with the ball.
- For the passes to work reliably, we will need a robot-detection that can tell us where the opponent's robots are to avoid passing to the enemy team.
- Our kicks need tuning, we will need very accurate kicks over long distances to make it work well.
- Maybe our role assignment needs rethinking, just adding more defenders and an additional bishop might not be the most effective strategy.
- With two additional robots sending messages, we will need to think about the message budget and what to send over Wi-Fi.

**Comment by knoellle** [comment]
Current rules can be found here: https://spl.robocup.org/downloads/
More specifically: https://spl.robocup.org/wp-content/uploads/SPL-Rules-master.pdf
