### ISSUE TITLE
Pepsi playernumber not working

### ISSUE THREAD

**Issue by julianschuler** [HULKs/hulk#393]
On the current main, `pepsi playernumber` seems to be broken. 

You can test this by executing 
```
./pepsi playernumber 21:1
```

Executing `git diff` reveals that the player number is not set (no changes to 
`etc/configuration/head.P0000074A03S84400010.json`).

Instead, the `etc/configuration/default.json` seems to get reformatted, though it should not be touched by pepsi at all.

**Comment by h3ndrk** [comment]
We are currently setting the player number in the top-level `default.json`. The `Scope` in the `repository` crate `set_player_number()` should contain `Ids::Head` instead of `Ids::All`.
