### ISSUE TITLE
impl From<Finished> for GameState { ... }

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#463]
We need to handle the transition from finished if the game controller controller accidentally presses finished and undoes it.

**Comment by h3ndrk** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnQ1bDVnNzltMTdxdXpyeXNmbW12eTlqcmkxeDhkbXFkNnlmcmIzYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/eN1jdQTP3AJHQBz2Ld/giphy.gif)

**Comment by okiwi6** [comment]
What is the state here? Is this still in progress?

**Comment by Vivituhh** [comment]
Still in progress, was halted because I needed to build a Game Controller.
