### ISSUE TITLE
Give some special treatment to special kicks

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#469]
Special kicks (kick-off, kick-in, goal kick, corner kick) should receive some special treatment. Some ideas:
- Force a forward kick (fixes #311)
- Use the large amount of time available to increase kick strength (conditionally, as corner kicks should not kick the ball out of the field, see #285) and kick accuracy

**Comment by schluis** [comment]
Is Season Goal 2024 and should be resolved with #541
