### ISSUE TITLE
Use `SubState` in ball search

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#514]
If information about possible ball positions can be extracted from the current game state, we should use this information for ball search.
Some ideas/examples of where to search when:
- corners during `SubState::CornerKick`
- goalkick positions during `SubState::GoalKick`
- field boundaries close to the last known ball position during `SubState::KickIn`
- penalty spot(s) during `SubState::PenaltyKick`

**Comment by MaikRe** [comment]
```PenaltyKick``` should not be used as we add a rule ball in this situation anyway and #801 prevents role switching into searcher.
However since #624 is now merged the ```GoalKick``` and ```CornerKick``` seem like excellent situations in which searching could be improved.
