### ISSUE TITLE
Request for Comments: Charging Box v2

### ISSUE THREAD

**Issue by julianschuler** [HULKs/hulk#519]
We need a new charging box! This issue tracks requirements and ideas for the next iteration of our charging box as well as proposed implementation options.

## Requirements

- More charging ports (at least 12)
- Self-contained (handle, enough space for cables, etc.)

## Nice to have

- Display with aliveness information etc.
- Interaction with connected robots (e.g. poweroff)
- No custom 230V wiring
- Low weight and small size
- Aligned LAN and charging cable ports

**Comment by julianschuler** [comment]
# "Single Cable" connection

## Concept

This is an completely different approach to the previous ones: Using the power over Ethernet 802.3bt Type 3 standard (also known as PoE++) one can transmit up to 51W via an ethernet cable. The NAO itself is not capable of charging via PoE, so a splitter with a CC/CV DC to DC step down converter which is near the NAO is used.

The charging box (except the display part) would simplify to a PoE++ capable switch, so the functional block diagram for the connection to one NAO is the following:

```
            ┌───────────────────────────────┐
NAO head ───┤ LAN out                       │
            │                  LAN (PoE) in ├───[...]─── PoE++ Switch
NAO body ───┤ DC (CC/CV) out                │
            └───────────────────────────────┘
```

This would get rid of all kind of alignment issues (since there is only one connector per NAO at the charging box), allows using more flexible cables of arbitrary lengths and easily extending the number of "charging ports" by building more splitters (assuming enough PoE++ ports left).

## Implementation options

The splitter board has to handle the PoE initialization as well as the CC/CV DC to DC conversion for charging. These can either be done with two ICs or using one combining both functions as the TPS23730. This requires designing a PCB as well as R&D into the construction of the CC/CV charger.

We should also consider whether reducing the charging speed is an option (~50W is just the maximum a NAO charger is able to provide, one should measure whether this is actually required), since PoE+ (802.3at Type 2) switches are more common and cheaper and the power electronic has to handle less power.

**Comment by PatrickGoettsch** [comment]
Question: yes there is an alignment problem. But why is that an issue. It is just an issue when you have to plug in the cable on the first day. But afterwards we need just the NAO side.
So no problem.
And xlr has the advantage that it would not slip out like audio Jack's could do.
And having some additional cabling next to NAO makes the wiring on the event with the Naos not better

**Comment by h3ndrk** [comment]
Current idea for torso holder:

![image](https://github.com/HULKs/hulk/assets/3900641/e473aa9e-9985-4a3c-a824-3369c9993892)

The charger cable can be integrated in the holder. A holder for the head is also planned, but maybe I will first print a torso holder and see if that works.

**Comment by schluis** [comment]
Box wurde gebaut
