### ISSUE TITLE
Walking Engine v2

### ISSUE THREAD

**Issue by oleflb** [HULKs/hulk#539]
We want a new walking engine!
- design: 4 weeks
- base implementation: 2 weeks
- parallel implementation: 8 weeks
- test + bugfix: 4 weeks

**Comment by schluis** [comment]
tracked by #685

**Comment by schmidma** [comment]
This issue is not yet resolved, as #685 is not yet merged

**Comment by MaikRe** [comment]
#685 is now merged!
