### ISSUE TITLE
Handle getting stuck leaning onto obstacles

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#56]
Walking can sometimes get stuck if the currently lifted foot never reaches the ground after a step. This can happen when the robot is leaning against something (goal post, other robot) and slightly tilted.

(Originally at: https://github.com/HULKs/nao/issues/4008)

**Comment by schmidma** [comment]
This is already implemented: https://github.com/HULKs/hulk/blob/9a643764b6a47b671680bc5437fc39a6e1ab15ae/crates/control/src/motion/walking_engine.rs#L367
