### ISSUE TITLE
Prevent invalid goal at kick off

### ISSUE THREAD

**Issue by Bendodroid** [HULKs/hulk#57]
Use weaker kick initially or maybe kick at an angle.
Might not be much of an issue in real game because we will usually have opposing robots, but it makes golden goals a worse benchmark than they could be.

(Originally at: https://github.com/HULKs/nao/issues/4028)

**Comment by schmidma** [comment]
This is maybe also a hint that we could adjust the benchmark routine?!

**Comment by PasGl** [comment]
This is legal now.
