### ISSUE TITLE
Add alsa-lib-devel to Fedora setup

### ISSUE THREAD

**Issue by ichbinJosi** [HULKs/hulk#620]
Add the package `alsa-lib-devel` to the Fedora dependencies.

**Comment by schmidma** [comment]
For which step is this dependency needed? The only occurrence of `alsa` should be in nao related code which is cross compiled using the Yocto SDK.

**Comment by ichbinJosi** [comment]
The Rust Analyzer in VSCode needed it for some build command.

**Comment by schluis** [comment]
This can be done in the files under `docs/setup`
