### ISSUE TITLE
HuLA formatting/clippy is not checked in CI

### ISSUE THREAD

**Issue by schmidma** [HULKs/hulk#63]
The `cargo fmt` only checks crates which are members of the root workspace.
HuLA (`tools/hula`) is explicitly excluded and not checked for formatting errors or clippy hints during CI checks.

There should be  additional tasks or commands to check HuLA.

**Comment by Bendodroid** [comment]
#33 ?

**Comment by Bendodroid** [comment]
Confirmed duplicate of #33, closing this.
