### ISSUE TITLE
Food Order  

### ISSUE THREAD

**Issue by JackyBloxx** [HULKs/hulk#642]
https://www.pizzahotchili.de/

Wir bestellen in einer halben stunde.
Kommentiert was ihr haben woll.

**Comment by knoellle** [comment]
Pizza Mexicana 25cm

**Comment by okiwi6** [comment]
Rollis-Goudakäse

**Comment by schmidma** [comment]
Pizza Italia
Pizzabrötchen

**Comment by h3ndrk** [comment]
Italia

**Comment by julianschuler** [comment]
Für Rasmus und mich: Pizza Funghi 60cm x 40 cm

**Comment by schluis** [comment]
Pizza Vegetarian 25cm
Pizza Bombay 25cm

**Comment by MaikRe** [comment]
Pizza Italia
