### ISSUE TITLE
Finalize Flora -> Twix Migration

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#66]
We have been exclusively supporting twix for a while now, leaving flora derelict.
Flora should be deleted but there are still some flora exclusive panels left.
Perhaps not all of them are necessary and some may be integrated into already existing panels.

Panels ported:
- [ ] Audio spectrums (map layer)
  - should be easy to port and helps a lot with diagnosing whistle detection issues.
- [x] Ball candidates (image overlay)
- [x] Ball filter
- [x] Behavior (map layer?)
  - port/create with behavior for 7v7 games
- [ ] Field border (image overlay)
- [x] Field color (implemented in image segments panel)
- [ ] Horizon (image overlay)
- [x] Image segments
- [x] Line detection (image overlay)
- [x] Line fitting (map layer)
- [x] Localization (map layer)
- [ ] Motion dispatching
- [ ] Odometry
- [x] Parameters
- [x] Path planning (map layer)
- [x] Projected field lines (image overlay)
- [x] Projected limbs (image overlay)
- [x] Raw image
- [x] Raw output
- [x] Robot detection (image overlay)

**Comment by schmidma** [comment]
There is no flora for some time now
