### ISSUE TITLE
Compilation error in Ubuntu 18.04

### ISSUE THREAD

**Issue by MarceloRother** [HULKs/hulk#665]
I had an issue with the codebase compilation. When I do any comands with the executable "pepsi" , the terminal returns the following message: "/usr/bin/env: invalid option -- 'S' Try '/usr/bin/env --help' for more information.".
I use a virtual machine (VirtualBox 7.0) with Ubuntu 18.04, and Cargo version 1.75.0. I did all the commands provided by Main Setup and Compiling for Webots for Ubuntu, without the section 2: "Install Webots Download webots from https://cyberbotics.com/ the XXXX.deb file and install it with".
An image with the terminal at next:
![imagem_2024-01-10_164349208](https://github.com/HULKs/hulk/assets/116506544/9e6baa44-3ab1-40c2-9620-bd58f8e75a86)

**Comment by giomf** [comment]
Yes, we have changed that in #640  to be a bit more best practices.

In your case, your coreutils version is outdated.
If I've seen it correctly, in ubuntu 18.04, corutils is at version 8.28. You need at least coreutils 8.30 to use the feature.

**Comment by giomf** [comment]
To be a little more clear. Updating to a newer version of Ubuntu should solve the problem.
Closing this issue. If you encounter more problems feel free to reopen.
