### ISSUE TITLE
Reduce implicity while writing code for the framework

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#74]
- Solve cycler instance names in another way rather than a magic enum CyclerInstances
- Explicitly mark first module
- Merge HULK binary and cycler crates into robotics domain crate. Create single framework crate that does all the code generation.
- Register modules more explicitly instead of discovering them automatically (maybe in Cargo.toml or in Rust code)

**Comment by schmidma** [comment]
This was all already implemented. The framework is two crates (source analysis and code generation), but hey ;)
