### ISSUE TITLE
Control cycler improvements

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#75]
- Remove 640 and 480 magic values in regards to camera resolution and introduce configuration parameters
- deduplicate project_penalty_area_on_images in localization and camera matrix calculator
- unflatten RobotKinematics to reduce the number of fields (and increase readability)
- Correctly capitalize all messages in errors, panics, unwraps, expects, ...
- Separate configuration types into own files or in other words, group them by robotics domain
- Reimplement exposing walking engine module variables as additional outputs

**Comment by schmidma** [comment]
Closing in favor of #751 #752 #753 #754 #755
