### ISSUE TITLE
Recheck and improve errors during development

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/hulk#77]
Recheck and improve errors thrown by the framework that happen when developing as a normal developer (e.g. when there is a non-produced output or lexer errors)

- Check that a required input has at least one optional path segment and an `Option` type
- Check that cycler instances exist that the user writes in the context structs
- When data types of e.g. inputs do not match with their e.g. outputs, we get meaningless errors for the mismatched types but no context, where it happened

**Comment by schmidma** [comment]
Some of it was implemented in #738, closing
