### ISSUE TITLE
Identify robot's IP and connect to it

### ISSUE THREAD

**Issue by DanielsAlmeida** [HULKs/hulk#775]
We are having some trouble connecting to the robot. With the last codebase we had, the robot directly spoke its IP when pressing the button on its chest. But now the same doesn't happen, changing the number depending on how we connect (local-link ipv4, tested with ubuntu 23.10 and windows 11). I'd like to know if there is a different connection method for NAO's operational system, some specific command or something similar.

**Comment by schluis** [comment]
Hey Daniel, what was your workflow like? We are having trouble figuring out exactly where the problem might be. Did you flash the robot with our image using ./pepsi gammaray?

**Comment by DanielsAlmeida** [comment]
Yes, as far as I know, we flashed the OS and everything is alright with it (but if you have any tips to make shure of its state, im all ears). The IPs that i found are on Aldebaran's pattern, and when I tried to connect to the robot via ssh it refused the connection (ssh nao@IP, also tested as root and pepsi instead of nao).

**Comment by MaikRe** [comment]
Hi Daniel! 
Did you adjust the hardware IDs ```meta-hulks/recipes-hulks/network-config/network-config/id_map.json``` when creating the image?

**Comment by DanielsAlmeida** [comment]
Hey Maik! No, I didnt adjust that, just flashed the image and sent it to the robot.

**Comment by schmidma** [comment]
If you setup a robot you need to flash our yocto image. The clean way to do this requires building your own linux distribution first. We provide all the necessary yocto recipes to build a custom linux distribution at https://github.com/HULKs/meta-nao . If you omit the `meta-hulks` layer in the build process, you get a clean distribution without any adjustments we especially need for our framework and setup. But as you want to run our framework, you are going to need this layer and all its recipes.

Our `meta-hulks` layer configures the network devices of each individual Nao head based on its head ID.
As @MaikRe pointed out, this happens here:

https://github.com/HULKs/meta-nao/blob/093c86bc0a3faaefa6c1ba5ec8be4b56514e4595/meta-hulks/recipes-hulks/network-config/network-config/configure_network

based on the head id mapping defined here:

https://github.com/HULKs/meta-nao/blob/093c86bc0a3faaefa6c1ba5ec8be4b56514e4595/meta-hulks/recipes-hulks/network-config/network-config/id_map.json

So you have two options:

1. build your own image: include the head IDs of your robots in the `id_map.json` and update the `configure_network` according to your team number, your robot will get your configured nao number and static ip assigned.
2. or just flash our image for testing and pretend to be a NAO of Team HULKs, just for testing. If the head id is not found in the `id_map.json`, the `configure_network` aborts (see [here](https://github.com/HULKs/meta-nao/blob/093c86bc0a3faaefa6c1ba5ec8be4b56514e4595/meta-hulks/recipes-hulks/network-config/network-config/configure_network#L9)) and the robot is configured using DHCP. This requires you to check your local DHCP server in the network what IP addresses are assigned.

In any way, you can afterwards connect via ssh at `nao@xxx.xxx.xxx.xxx` without any password or via our custom `pepsi` tool using `pepsi shell NAO_NUMBER`.

Hope this helps, if you have any further questions, feel free to ask.

**Comment by MaikRe** [comment]
No further questions in last 2 months, issue is considered resolved
