### ISSUE TITLE
Post-game task: Investigate why our keeper doesn't enter the goal

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#859]
No. 1:39 Refused to enter the goal during ready, only doing so after entering playing.

**Comment by MaikRe** [comment]
Cannot checked because replayer did not record anything

**Comment by MaikRe** [comment]
We had robot obstacle detections. Likely an issue with sonar.  Same happened in #862 
![image](https://github.com/HULKs/hulk/assets/87246463/4ebb206e-3be1-4ef6-b53f-68e6696c3812)
