### ISSUE TITLE
Post-game task: Investigate center circle incursions

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#861]
No. 6:41 and 7:38 illegally entered the center circle towards the end of the first half of our first game today (and then both didn't kick the ball). Investigate.

**Comment by MaikRe** [comment]
Cannot checked because replayer did not record anything

**Comment by MaikRe** [comment]
Ball detection was off, robot thought that ball had moved and is thus considered free.
Is not a behavioral issue.
Most likely the camera matrix calibration was off as it had to be recalibrated after the test game.

![image](https://github.com/HULKs/hulk/assets/87246463/b939a890-8601-4d4f-b075-00e09bba4ec8)

**Comment by MaikRe** [comment]
Center circle incursions also occurred in our game against Naova today.
Our game controller state gets set to playing earlier than it should.
This needs to be investigated with spl network message replay if and when this occurs again.
