### ISSUE TITLE
Post-game task: Investigate walk-in jockeling

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#864]
No. 4:37, after walking in from being penalized, started walking on the spot for a while before walking to the intended position. Watch the replay, and investigate.

**Comment by knoellle** [comment]
Was this the field border obstacle issue, can this be closed then?

**Comment by Narcha** [comment]
Most likely yes, but I'm not sure because I haven't watched the replay yet.

**Comment by MaikRe** [comment]
Outdated
