### ISSUE TITLE
Opponent penalties for visual referee

### ISSUE THREAD

**Issue by knoellle** [HULKs/hulk#877]
When detecting the visual referee hand signal for Initial -> Ready, delay a few seconds before deciding.
If an opponent robot is penalized during this time (we get this information from the game controller), ignore the signal.

This assumes that whatever false positive we saw was picked up by the opposing team as well.

**Comment by knoellle** [comment]
Fixed by #1086

**Comment by MaikRe** [comment]
Although this seemed to be the case during testing it was found in the testgame last week that this is not 100% functional.
#1112 should fix this
