### ISSUE TITLE
Post-game task: Fix keeper walk-in

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#878]
In our games today and yesterday, our keeper fails to walk to it's set position correctly in the ready phase, only doing so after entering `Playing`.

**Comment by PatrickGoettsch** [comment]
Maybe, it is an issue of many falso positive detected obstacles. We observed this during testing dynamic goal posts

**Comment by MaikRe** [comment]
This was definitely an issue from falsely detected feet and some sonar obstacles which did not occur when we turned off feet detection and properly adjusted jerseys again before games. False obstacles should be further studied independently of games for which #867 was opened
