### ISSUE TITLE
Path planning should be failable

### ISSUE THREAD

**Issue by Narcha** [HULKs/hulk#930]
Currently, when a robot sees the ball but is unable to plan a path to it, like for example when he is beyond the field border obstacle,
path planning returns a "zero path", which terminates at the robot's current position (not the ball). The TTRKP in this case is zero, and thus he claims the striker role.

Instead, path planning should return an optional path, returning `None` if there is no viable path to reach the requested target.
The step planner should just stop walking when asked to plan steps for a `None` path. Optionally, add some audiovisual indicator to let us know that path planning failed.

**Comment by Narcha** [comment]
@MaikRe
Oxford: [failable](https://www.oxfordlearnersdictionaries.com/us/definition/english/failable) vs [fallible](https://www.oxfordlearnersdictionaries.com/us/definition/english/fallible)
Cambridge: [failable](https://dictionary.cambridge.org/spellcheck/english/?q=failable) vs [fallible](https://dictionary.cambridge.org/dictionary/english/fallible)
Britannica: [failable](https://www.britannica.com/dictionary/eb/spelling/failable) vs [fallible](https://www.britannica.com/dictionary/fallible)
Merriam-Webster: [failable](https://www.merriam-webster.com/dictionary/failable) vs [fallible](https://www.merriam-webster.com/dictionary/fallible)

**Comment by schluis** [comment]
Solved by #1051
