### ISSUE TITLE
Visual Referee keypoints confidence filtering

### ISSUE THREAD

**Issue by ThagonDuarte** [HULKs/hulk#985]
Use the confidences of the pose keypoints, to filter that whole pose. If the hand keypoints have bad confidences for example, throw away that whole pose. Additionally use at least to different confidence thresholds for the filtering. One for the group of keypoints that are relevant for the pose filtering with a higher threshold and one for the other keypoints with a lower threshold.

**Comment by knoellle** [comment]
Fixed by #1094
