### ISSUE TITLE
First build takes ages because of `openvino` git dependency

### ISSUE THREAD

**Issue by schmidma** [HULKs/hulk#988]
When building the repository from a fresh state (no cargo registry caches, etc.), the `Updating` stage takes ages as it is cloning several tens of git submodules originating from https://github.com/intel/openvino-rs.git

As soon as openvino-rs releases a new version that includes our required changes, we should opt that release to speed up the build process. Alternatively we can search for an option to speedup or even skip this cloning of submodules. Maybe there is a way and openvino-rs does not need all of these dependencies.

**Comment by oleflb** [comment]
Fixed by #1048
