### ISSUE TITLE
Penalty Shootout Keeper

### ISSUE THREAD

**Issue by oleflb** [HULKs/hulk#997]
Our Keeper jumps directly after going down, likely because the ball gets velocity due to the sensor lag.
Ideas:
~- Just go down earlier (anyways good idea)~
~- ball only gets velocity in Play~
~- use whistle detection?~
- [ ] Ask the Devils if they would provide their Keeper motion since it looks soooo much better than ours
- [x] Implement the wide stance from the wide stance into the current keeper behavior

**Comment by MaikRe** [comment]
1. I don't know/think we can go down much earlier. The goal keeper is placed while the game state is set, and this only goes into playing through the whistle. Assuming the robot hears the whistle, it immediately does the action ```PrepareJump```.
3. We use the whistle detection, thats how we know when we are allow to prepare the jump
4. Technically speaking the Devil's motion could eventually be illegal as it includes a T-Pose. If the attacking robot waits 10 seconds to do the kick the goalkeeper either needs to move its arms back in, or it is called for wide stance and a goal is automatically counted.

**Comment by MaikRe** [comment]
As for the ball velocity, we only do penalty direction estimation in playing, it may be good to wait until the sit down motion is finished for this to happen?
```rust
(PrimaryState::Playing, GamePhase::PenaltyShootout { .. }, ..)
            | (PrimaryState::Playing, _, Some(SubState::PenaltyKick), Team::Opponent) => {
                if let PenaltyShotDirection::NotMoving = self.last_shot_direction {
                    if (context.ball_position.position.x()
                        - context.field_dimensions.penalty_marker_distance)
                        .abs()
                        > *context.moving_distance_threshold
```
but I have no idea how that would be best implemented.
The other issue sort of relates to #1043, in that we do the estimation of movement purely based on the location of the penalty marker. i.e. if the camera matrix is off (which can easily happen if the robot has already jumped once) then this estimation will likely immediately trigger a penalty shot estimation and the robot jumps.

Therefore we once again need an estimation for this situation which does a relative movement of the ball or we need some other method which properly gives the ball velocity

**Comment by MaikRe** [comment]
I am modifying the description to match the current state of what could be done, or should be implemented

**Comment by MaikRe** [comment]
Besides the center squat motion that @larskna  and I were working on it is probably also necessary to reintroduce the velocity check proposed by @tuxbotix in #492 as a robot with a messed up camera matrix will see the ball move closer to itself during the `armsupsquat` motion which triggers the jump. Interestingly enough the ball does not receive any velocity in this situation.
Another possibility is the wait until the robot has fully sat down to determine where the ball should be coming from, but this delays us by a few seconds and is detrimental against quick opponents
