### ISSUE TITLE
Deny False Positives in Visual Referee Detection

### ISSUE THREAD

**Issue by oleflb** [HULKs/hulk#999]
- [ ] use horizon check
- [ ] use height check
- [x] use keypoint confidence
- ~maybe check "redness" at hand keypoints (remember the referee is wearing gloves)~

**Comment by MaikRe** [comment]
Although not relevant for this RoboCup, I would find it troubling if checking for redness was the solution to this as the red gloves are to be removed next robocup

**Comment by schmidma** [comment]
Is this fully resolved since #1094 was merged?

**Comment by knoellle** [comment]
AFAIK not, or at least not as proposed.
The PR only uses confidences and relative keypoint positions for filtering.
If I understand the original issue text correctly, the idea was to use the referee height as well to differentiate it from robots.
Not quite sure what is meant by the horizon check.

However, if the detection now works reliably enough already, we could still close the issue.
Keep in mind that we also have the voting and the sacrificial nao.

@ThagonDuarte?

**Comment by oleflb** [comment]
I also vote for closing, what do you think @ThagonDuarte?

**Comment by ThagonDuarte** [comment]
Yes, I agree.
